wandb_version: 1

env_name:
  desc: null
  value: so2
learning rate:
  desc: null
  value: 0.001
iterations:
  desc: null
  value: 300
optimizer:
  desc: null
  value: adamw
batchsize:
  desc: null
  value: 64
gpt_n_embd:
  desc: null
  value: 12
gpt_n_layer:
  desc: null
  value: 4
gpt_n_head:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    python_version: 3.7.7
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.4.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700337179.831208
    t:
      1:
      - 1
      - 11
      - 55
      2:
      - 1
      - 11
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.7.7
      5: 0.15.12
      6: 4.4.2
      8:
      - 5
      13: darwin-x86_64
