inherit: 
    - wandb.yaml

model:
    family: gpt
    name: large
    n_embd: 256
    n_layer: 12
    n_head: 8
    n_positions: 1024

task: 
    matrix_dim: 2

training:
    batch_size: 256
    optim: adamw
    num_iterations: 300
    traj_len: 256
    lr: 0.0005

    save_every_steps: 20
    save_path: ./results/.
    graph_path: ./plots/.

testing:
    num_tests: 100
    traj_len: 256