inherit: 
    - models/gpt_large.yaml
    - wandb.yaml

task: 
    matrix_dim: 2
    traj_len: 100

training:
    batch_size: 64
    lr: 0.001
    optim: adam
    num_iterations: 300

    save_every_steps: 1000
    save_path: ./results/.
    graph_path: ./plots/.

num_tests: 100
