inherit: 
    - models/gpt_medium.yaml
    - wandb.yaml

task: 
    matrix_dim: 2
    traj_len: 15
    
    # env_name: so2

training:
    batch_size: 64
    lr: 0.001
    optim: adam
    num_iterations: 3000

    save_every_steps: 1000
    save_path: ./results/.
    graph_path: ./plots/.

num_tests: 10
