inherit: 
    - models/gpt_medium.yaml
    - wandb.yaml

task: 
    matrix_dim: 2
    traj_len: 2000 #, 5000, 10000 
    
    # env_name: so2

training:
    batch_size: 256
    lr: 0.0006
    optim: adamw
    num_iterations: 80

    save_every_steps: 1000
    save_path: ./results/.
    graph_path: ./plots/.

num_tests: 200
