inherit: 
    - wandb.yaml

model:
    family: gpt
    n_embd: 512
    n_layer: 24
    n_head: 16
    n_positions: 1024

task: 
    matrix_dim: 2

training:
    batch_size: 256
    lr: 0.0006
    optim: adamw
    num_iterations: 100
    traj_len: 256

    save_every_steps: 10
    save_path: ./results/.
    graph_path: ./plots/.

testing:
    num_tests: 1000
    traj_len: 256