inherit: 
    - wandb.yaml

model:
    family: gpt
    name: small
    n_embd: 16
    n_layer: 2
    n_head: 2
    n_positions: 1024

task: 
    matrix_dim: 2

training:
    batch_size: 256
    optim: adamw
    num_iterations: 620
    traj_len: 256
    lr: 0.01

    save_every_steps: 20
    save_path: ./results/.
    graph_path: ./plots/.

testing:
    num_tests: 2001
    traj_len: 256